version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers-legacy
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler -v 2.2.19
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Bundle install for default environment
          command: bundle install
      - run:
          name: Bundle install for test environment
          command: RAILS_ENV=test bundle install
      - run:
          name: Run rubocop
          command: bundle exec rubocop .
      - run:
          name: Run Brakeman
          command: bundle exec brakeman .
      - run:
          name: Run Rspec
          command: bundle exec Rspec .
